### ISSUE TITLE
a compilation error

### ISSUE THREAD

**Issue by jaxingLee** [QuMuLab/planner-for-relevant-policies#10]
`$ ./build_all.sh
Makefile:46: OS detection failed -- setting to Linux and hoping for the best!
make: Nothing to be done for 'default'.
Makefile:154: OS detection failed -- setting to Linux and hoping for the best!
g++ -Iext -g -Wall -W -Wno-sign-compare -Wno-deprecated -ansi -pedantic -Werror -O3 -DNDEBUG -fomit-frame-pointer -c exact_timer.cc -o .obj/exact_timer.release.o
exact_timer.cc:13:9: error: "CLOCK_PROCESS_CPUTIME_ID" redefined [-Werror]
   13 | #define CLOCK_PROCESS_CPUTIME_ID (clockid_t)2
      |         ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from C:/msys64/mingw64/include/time.h:323,
                 from C:/msys64/mingw64/include/pthread.h:69,
                 from C:/msys64/mingw64/include/c++/14.2.0/x86_64-w64-mingw32/bits/gthr-default.h:3
,
                 from C:/msys64/mingw64/include/c++/14.2.0/x86_64-w64-mingw32/bits/gthr.h:157,
                 from C:/msys64/mingw64/include/c++/14.2.0/ext/atomicity.h:35,
                 from C:/msys64/mingw64/include/c++/14.2.0/bits/ios_base.h:39,
                 from C:/msys64/mingw64/include/c++/14.2.0/ios:44,
                 from C:/msys64/mingw64/include/c++/14.2.0/ostream:40,
                 from utilities.h:5,
                 from exact_timer.cc:3:
C:/msys64/mingw64/include/pthread_time.h:42:9: note: this is the location of the previous definition
   42 | #define CLOCK_PROCESS_CPUTIME_ID    2
      |         ^~~~~~~~~~~~~~~~~~~~~~~~
cc1plus.exe: all warnings being treated as errors
make: *** [Makefile:325: .obj/exact_timer.release.o] Error 1`

An error occurred during compilation. Could you please tell me what this is about?

**Comment by haz** [comment]
Few things here...

1. PR2 is preferred to PRP, so you should be using [that](https://mulab.ai/project/pr2/) instead.
2. Looks like you're trying to build on windows. That isn't supported. Please use WSL if you're on windows, or at the very least, the appropriate docker environment.
