### ISSUE TITLE
ImportError: No module named krrt.utils

### ISSUE THREAD

**Issue by Tridu33** [QuMuLab/planner-for-relevant-policies#3]
```python
ImportError: No module named krrt.utils
```
is `krrt` this [package](https://github.com/QuMuLab/krtoolkit/tree/a09525cb4835dc06eedf79f7465ee5da527cbb0d/krrt)?

**Comment by haz** [comment]
It is indeed -- an old library that would likely need an overhaul to run. What are you using that requires it?

**Comment by Tridu33** [comment]
policy_experiment.py

**Comment by haz** [comment]
Figured it out then?

**Comment by haz** [comment]
Tbh, I'm a little confused about the string of issues being opened/closed. If you're troubleshooting, head on over to https://slack.planning.domains/ and you can find myself and the planning community there.

**Comment by Tridu33** [comment]
> Figured it out then?

yes, i downloaded the package `krrt` and `policy_experiment.py` can run well.
