### ISSUE TITLE
Addressing the error message ./planner-for-relevant-policies/src/search/downward-release: No such file or directory

### ISSUE THREAD

**Issue by AnjelicaB** [QuMuLab/planner-for-relevant-policies#6]
When running search for my domain and problem files through PRP, it produced an error:

3. Running search
./planner-for-relevant-policies/src/search/downward ipc policy-repair
This is a unit task.
./planner-for-relevant-policies/src/search/downward-release --heuristic "h=ff(cost_type=1)" --search "lazy_greedy([h],preferred=[h])" --random-seed 814102613 < output
./planner-for-relevant-policies/src/search/downward: line 166: ./planner-for-relevant-policies/src/search/downward-release: No such file or directory

How can this error be addressed?

**Comment by haz** [comment]
Looks like you haven't compiled the planner. How are you trying to run things? Might be easier through `planutils`, if you haven't already tried.

**Comment by AnjelicaB** [comment]
I'll try downloading planutils. But when I try to build prp `% ./build_all`, it produces the error 
`make: Nothing to be done for 'default'.`
`g++ -Iext -g -Wall -W -Wno-sign-compare -Wno-deprecated -ansi -pedantic -Werror -O3 -DNDEBUG -fomit-frame-pointer -c planner.cc -o .obj/planner.release.o`
`In file included from planner.cc:2:`
`In file included from ./operator.h:12:`
`In file included from ./state.h:5:`
`./state_id.h:4:10: fatal error: 'hash_set' file not found`
`#include <hash_set>`
`         ^~~~~~~~~~`
`1 error generated.`

**Comment by haz** [comment]
Have you installed the dependencies for FastDownward and it's derivatives (like PRP)?

https://www.fast-downward.org/ObtainingAndRunningFastDownward

**Comment by AnjelicaB** [comment]
Hum, but the manifest file from planutils on prp didn't list any dependencies...(I'm also unable to install prp from planutils). Either way, I tried installing the dependencies according to their instructions for Linux (I use macOS) `sudo apt install cmake g++ git make python3`, but it gave me the error 
`The operation couldn’t be completed. Unable to locate a Java Runtime that supports apt.`
`Please visit http://www.java.com for information on installing Java.`
Even though I have Java installed. But for some reason, I am able to compile FastDownward...

**Comment by haz** [comment]
Ah, well you didn't specify that it was on a Mac -- it's an OS largely unsupported by the vast majority of planners. If you need to run things on a Mac, then using docker, and planutils through it, is your best bet.

```bash
docker pull aiplanning/planutils
docker run --privileged -it aiplanning/planutils
```

Closing the issue since this is largely due to an unsupported OS for the planner.
